SET NAMES utf8mb4;

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'cms-ringan', 'CMS Ringan', 'Tag untuk artikel tentang CMS ringan yang cepat dan efisien.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'cms-ringan');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'seo-cms', 'SEO CMS', 'Tag untuk artikel tentang CMS yang ramah SEO.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'seo-cms');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'company-profile', 'Company Profile', 'Tag untuk artikel website company profile.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'company-profile');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'landing-page', 'Landing Page', 'Tag untuk artikel landing page dan halaman konversi.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'landing-page');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'blog-bisnis', 'Blog Bisnis', 'Tag untuk artikel blog bisnis dan strategi konten.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'blog-bisnis');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'manajemen-konten', 'Manajemen Konten', 'Tag untuk artikel pengelolaan konten yang rapi.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'manajemen-konten');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'performa-website', 'Performa Website', 'Tag untuk artikel performa website dan kecepatan akses.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'performa-website');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'custom-tema', 'Custom Tema', 'Tag untuk artikel kustomisasi tema dan tampilan.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'custom-tema');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'website-bisnis', 'Website Bisnis', 'Tag untuk artikel website bisnis yang profesional.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'website-bisnis');

INSERT INTO `tags` (`slug_tags`, `name_tags`, `info_tags`, `photo_tags`, `created_at`, `updated_at`, `user_id`)
SELECT 'produktivitas-tim', 'Produktivitas Tim', 'Tag untuk artikel efisiensi kerja dan produktivitas tim konten.', '/assets/img/dummy-cover.svg', '2026-03-10 09:00:00', '2026-03-10 09:00:00', 1
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `tags` WHERE `slug_tags` = 'produktivitas-tim');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'manfaat-aiticms-lite-untuk-website-bisnis', 1, 'Manfaat Aiticms-Lite untuk Website Bisnis', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-01.svg', '<p>Aiticms-Lite adalah pilihan tepat untuk bisnis yang membutuhkan website cepat, rapi, dan mudah dikelola. CMS ini dirancang ringan sehingga halaman dapat dimuat lebih efisien, baik di desktop maupun perangkat mobile. Bagi bisnis yang ingin tampil profesional tanpa proses teknis yang rumit, Aiticms-Lite memberi fondasi yang sederhana tetapi tetap kuat.</p><h2>Kelebihan utama Aiticms-Lite</h2><p>Salah satu kelebihan Aiticms-Lite adalah struktur kontennya mudah dipahami. Tim dapat menambah artikel, mengatur tag, dan mengelola halaman penting tanpa alur kerja yang membingungkan. Hal ini membantu bisnis menjaga konsistensi publikasi konten dan memperkuat visibilitas merek di mesin pencari.</p><ul><li>Ringan dan cepat diakses</li><li>Mudah dipakai untuk artikel dan company profile</li><li>Memudahkan optimasi SEO on-page</li><li>Cocok untuk pengembangan website bisnis jangka panjang</li></ul><p>Dengan kombinasi performa dan kemudahan pakai, Aiticms-Lite cocok untuk website bisnis yang ingin tumbuh lewat konten organik. Bisnis tidak perlu memulai dari sistem yang terlalu kompleks jika kebutuhan utamanya adalah publikasi konten, halaman profil, dan struktur website yang rapi.</p>', NULL, 'cms ringan,website bisnis,seo cms', '2026-03-10 09:01:00', '2026-03-10 09:01:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'manfaat-aiticms-lite-untuk-website-bisnis');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'kelebihan-aiticms-lite-cms-ringan-untuk-company-profile', 1, 'Kelebihan Aiticms-Lite, CMS Ringan untuk Company Profile', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-02.svg', '<p>Banyak perusahaan membutuhkan website company profile yang cepat online, mudah diperbarui, dan tetap enak dibuka pengunjung. Aiticms-Lite menjawab kebutuhan itu lewat sistem yang ringan dan fokus pada pengelolaan konten inti. Anda dapat menampilkan profil perusahaan, layanan, kontak, dan artikel pendukung dalam satu alur kerja yang sederhana.</p><h2>Mengapa cocok untuk company profile</h2><p>Aiticms-Lite tidak membebani tim dengan fitur yang tidak relevan. Fokusnya adalah kemudahan menulis konten, memperbarui halaman, dan mengatur tampilan dasar website agar tetap profesional. Struktur seperti ini membuat proses maintenance lebih hemat waktu.</p><ul><li>Panel admin mudah dipahami</li><li>Halaman profil dan artikel dapat dikelola dari satu CMS</li><li>Lebih efisien untuk tim marketing dan admin</li><li>Memberi pengalaman akses yang cepat bagi calon klien</li></ul><p>Jika tujuan website Anda adalah membangun kepercayaan, Aiticms-Lite memberi dasar yang tepat. CMS ini cocok untuk perusahaan jasa, software house, konsultan, dan brand lokal yang ingin punya company profile profesional dengan manajemen konten yang praktis.</p>', NULL, 'cms ringan,company profile,website bisnis', '2026-03-10 09:02:00', '2026-03-10 09:02:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'kelebihan-aiticms-lite-cms-ringan-untuk-company-profile');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'alasan-aiticms-lite-cocok-untuk-blog-seo', 3, 'Alasan Aiticms-Lite Cocok untuk Blog SEO', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-03.svg', '<p>Blog yang baik membutuhkan CMS yang tidak menghambat proses menulis, mengedit, dan mempublikasikan konten. Aiticms-Lite membantu tim fokus pada kualitas artikel karena proses administrasinya dibuat ringkas. Dari sisi SEO, struktur artikel, slug, tag, dan halaman baca sudah mendukung kebutuhan dasar optimasi mesin pencari.</p><h2>Nilai tambah untuk strategi konten</h2><p>Dengan CMS yang ringan, waktu muat halaman menjadi lebih efisien. Ini penting karena kecepatan halaman ikut memengaruhi pengalaman pengguna dan kualitas trafik organik. Selain itu, pengelolaan slug dan tag memudahkan pembentukan cluster topik pada blog bisnis.</p><ul><li>Mudah membuat slug artikel yang rapi</li><li>Tag membantu pengelompokan topik</li><li>Konten dapat dipublikasikan konsisten</li><li>Struktur sederhana memudahkan audit SEO</li></ul><p>Aiticms-Lite cocok dipakai untuk blog perusahaan, media niche, maupun blog edukasi produk. Jika target Anda adalah pertumbuhan organik yang konsisten, CMS ini memberi fondasi yang efisien tanpa beban sistem yang berlebihan.</p>', NULL, 'seo cms,blog bisnis,cms ringan', '2026-03-10 09:03:00', '2026-03-10 09:03:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'alasan-aiticms-lite-cocok-untuk-blog-seo');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'keunggulan-aiticms-lite-untuk-landing-page-cepat', 2, 'Keunggulan Aiticms-Lite untuk Landing Page Cepat', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-04.svg', '<p>Landing page membutuhkan fokus pada kecepatan, kejelasan pesan, dan kemudahan update. Aiticms-Lite mendukung kebutuhan tersebut karena tampilannya dapat dijaga tetap ringan sambil tetap memberi ruang untuk mengelola konten promosi secara cepat. Tim marketing tidak perlu mengubah banyak hal teknis hanya untuk memperbarui informasi penting.</p><h2>Efisien untuk halaman promosi</h2><p>Landing page yang cepat lebih baik untuk iklan, kampanye organik, dan pengalaman pengguna mobile. Dengan Aiticms-Lite, Anda dapat mengatur halaman kampanye, menambahkan artikel pendukung, dan menyusun struktur website yang mendukung konversi.</p><ul><li>Ringan untuk kebutuhan promosi digital</li><li>Mudah diperbarui saat kampanye berjalan</li><li>Mendukung integrasi konten artikel pendukung</li><li>Cocok untuk website jasa dan produk digital</li></ul><p>Aiticms-Lite menjadi solusi masuk akal untuk bisnis yang ingin landing page cepat tayang dan tetap terhubung dengan ekosistem konten di dalam website.</p>', NULL, 'landing page,performa website,website bisnis', '2026-03-10 09:04:00', '2026-03-10 09:04:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'keunggulan-aiticms-lite-untuk-landing-page-cepat');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'fitur-aiticms-lite-yang-memudahkan-manajemen-konten', 3, 'Fitur Aiticms-Lite yang Memudahkan Manajemen Konten', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-05.svg', '<p>Salah satu alasan memakai Aiticms-Lite adalah kemudahan manajemen konten. CMS ini membantu tim menyimpan fokus pada isi artikel, halaman, dan struktur informasi tanpa harus menghadapi panel yang terlalu padat. Bagi bisnis yang ingin bergerak cepat, kesederhanaan ini sangat berharga.</p><h2>Manajemen konten lebih rapi</h2><p>Pengguna dapat mengatur judul, slug, tag, gambar, dan konten artikel dari alur yang langsung ke inti. Ini membantu proses editorial menjadi lebih stabil dan memudahkan pengelolaan website dalam jangka panjang.</p><ul><li>Pengisian artikel lebih cepat</li><li>Tag dan kategori membantu pengarsipan topik</li><li>Konten mudah dipelihara oleh tim kecil</li><li>Lebih efisien untuk kebutuhan update rutin</li></ul><p>Dengan manajemen konten yang rapi, bisnis dapat menjaga kualitas publikasi sekaligus mempercepat waktu produksi halaman baru. Aiticms-Lite sangat cocok bagi pemilik usaha yang membutuhkan CMS praktis untuk website aktif.</p>', NULL, 'manajemen konten,produktivitas tim,cms ringan', '2026-03-10 09:05:00', '2026-03-10 09:05:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'fitur-aiticms-lite-yang-memudahkan-manajemen-konten');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'mengapa-aiticms-lite-efisien-untuk-tim-kecil', 1, 'Mengapa Aiticms-Lite Efisien untuk Tim Kecil', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-06.svg', '<p>Tidak semua bisnis memiliki tim digital yang besar. Karena itu, CMS yang efisien sering lebih penting daripada CMS yang penuh fitur. Aiticms-Lite dirancang agar tim kecil tetap bisa mengelola website bisnis secara konsisten tanpa menambah kompleksitas kerja harian.</p><h2>Praktis untuk operasional harian</h2><p>Tim dapat menambah artikel, memperbarui halaman layanan, dan menyesuaikan informasi penting dengan cepat. Alur kerja yang ringkas membantu mengurangi waktu adaptasi dan menekan risiko salah input saat update konten.</p><ul><li>Cocok untuk admin, marketing, dan owner bisnis</li><li>Mengurangi beban pelatihan internal</li><li>Perubahan konten bisa dilakukan lebih cepat</li><li>Memudahkan kolaborasi tim kecil</li></ul><p>Bagi usaha yang ingin website tetap aktif tanpa biaya operasional besar, Aiticms-Lite memberi keseimbangan antara fungsi, kecepatan, dan kemudahan pengelolaan.</p>', NULL, 'produktivitas tim,website bisnis,manajemen konten', '2026-03-10 09:06:00', '2026-03-10 09:06:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'mengapa-aiticms-lite-efisien-untuk-tim-kecil');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'aiticms-lite-mudah-dikustom-untuk-brand-bisnis', 2, 'Aiticms-Lite Mudah Dikustom untuk Brand Bisnis', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-07.svg', '<p>Setiap brand memiliki kebutuhan tampilan yang berbeda. Aiticms-Lite memberi ruang yang cukup untuk menyesuaikan tema, struktur halaman, dan elemen visual tanpa membuat sistem inti menjadi berat. Pendekatan ini penting untuk bisnis yang ingin tampil khas tetapi tetap menjaga performa website.</p><h2>Fleksibel tanpa membuat sistem rumit</h2><p>Kustomisasi yang baik bukan hanya soal warna dan font. Yang lebih penting adalah kemudahan menyesuaikan halaman dengan kebutuhan promosi, profil layanan, dan jalur konversi pengguna. Aiticms-Lite mendukung tujuan itu dengan struktur yang sederhana.</p><ul><li>Tema lebih mudah disesuaikan</li><li>Cocok untuk branding perusahaan</li><li>Tidak membebani proses update konten</li><li>Lebih mudah dipelihara dalam jangka panjang</li></ul><p>Jika bisnis membutuhkan CMS yang fleksibel tetapi tidak ingin tenggelam dalam konfigurasi teknis yang berlebihan, Aiticms-Lite adalah opsi yang relevan.</p>', NULL, 'custom tema,company profile,website bisnis', '2026-03-10 09:07:00', '2026-03-10 09:07:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'aiticms-lite-mudah-dikustom-untuk-brand-bisnis');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'kelebihan-aiticms-lite-dengan-tag-dan-struktur-seo', 3, 'Kelebihan Aiticms-Lite dengan Tag dan Struktur SEO', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-08.svg', '<p>Optimasi SEO tidak hanya bergantung pada isi artikel. Struktur konten juga berperan besar. Aiticms-Lite memberi kemudahan dalam pengelolaan slug, tag, dan organisasi artikel sehingga website lebih mudah berkembang menjadi pusat konten yang rapi.</p><h2>Tag membantu distribusi topik</h2><p>Dengan penggunaan tag yang konsisten, bisnis dapat membangun hubungan antar artikel dan memudahkan pengunjung menemukan topik yang relevan. Ini juga membantu strategi internal linking dan pengelompokan tema konten.</p><ul><li>Slug artikel lebih mudah diatur</li><li>Tag memudahkan pencarian topik terkait</li><li>Struktur konten lebih siap untuk SEO dasar</li><li>Website lebih mudah dikembangkan menjadi blog aktif</li></ul><p>Aiticms-Lite cocok bagi pemilik website yang ingin mengelola konten secara rapi sambil menjaga peluang pertumbuhan trafik organik dari mesin pencari.</p>', NULL, 'seo cms,manajemen konten,blog bisnis', '2026-03-10 09:08:00', '2026-03-10 09:08:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'kelebihan-aiticms-lite-dengan-tag-dan-struktur-seo');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'aiticms-lite-solusi-cms-sederhana-tanpa-ribet', 1, 'Aiticms-Lite, Solusi CMS Sederhana Tanpa Ribet', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-09.svg', '<p>Banyak pemilik website hanya membutuhkan CMS yang cepat dipahami dan mudah dipakai sehari hari. Aiticms-Lite hadir sebagai solusi CMS sederhana tanpa ribet, sehingga pengguna bisa fokus pada publikasi dan pengembangan bisnis, bukan sibuk mengelola sistem yang terlalu kompleks.</p><h2>Lebih fokus pada hasil</h2><p>Kesederhanaan membuat pengelolaan website terasa ringan. Ini penting untuk brand yang ingin bergerak cepat, terutama saat harus memperbarui artikel, halaman layanan, atau informasi promosi.</p><ul><li>Lebih mudah dioperasikan</li><li>Meminimalkan langkah teknis yang tidak perlu</li><li>Cocok untuk website bisnis skala kecil sampai menengah</li><li>Membantu tim tetap fokus pada konten dan promosi</li></ul><p>Dengan pendekatan yang praktis, Aiticms-Lite memberi jalan yang lebih efisien untuk bisnis yang ingin website aktif dan profesional tanpa proses administrasi yang melelahkan.</p>', NULL, 'cms ringan,website bisnis,produktivitas tim', '2026-03-10 09:09:00', '2026-03-10 09:09:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'aiticms-lite-solusi-cms-sederhana-tanpa-ribet');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'keunggulan-aiticms-lite-untuk-performa-dan-user-experience', 2, 'Keunggulan Aiticms-Lite untuk Performa dan User Experience', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-10.svg', '<p>Website yang cepat lebih nyaman dipakai dan lebih dipercaya pengunjung. Aiticms-Lite memiliki karakter ringan yang membantu menjaga performa halaman tetap baik. Ini berdampak langsung pada user experience, terutama untuk pengunjung mobile yang sensitif terhadap waktu muat.</p><h2>Pengalaman pengguna lebih baik</h2><p>CMS yang tidak berlebihan membantu halaman tampil lebih efisien. Ketika pengunjung mudah mengakses artikel, profil bisnis, dan halaman layanan, peluang interaksi dan konversi akan meningkat.</p><ul><li>Waktu muat halaman lebih efisien</li><li>Tampilan nyaman di perangkat mobile</li><li>Mendukung pengalaman baca artikel yang lebih baik</li><li>Baik untuk citra website profesional</li></ul><p>Aiticms-Lite layak dipilih bila Anda memprioritaskan performa website dan pengalaman pengguna sebagai bagian dari strategi digital jangka panjang.</p>', NULL, 'performa website,seo cms,cms ringan', '2026-03-10 09:10:00', '2026-03-10 09:10:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'keunggulan-aiticms-lite-untuk-performa-dan-user-experience');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'alasan-memilih-aiticms-lite-untuk-website-produk-digital', 3, 'Alasan Memilih Aiticms-Lite untuk Website Produk Digital', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-11.svg', '<p>Produk digital membutuhkan website yang bisa menjelaskan manfaat produk dengan jelas dan tetap mudah diperbarui. Aiticms-Lite cocok untuk kebutuhan tersebut karena memudahkan pengelolaan halaman produk, artikel edukasi, dan konten pendukung lain yang membantu konversi.</p><h2>Cocok untuk edukasi dan promosi produk</h2><p>Website produk digital biasanya membutuhkan kombinasi antara halaman utama yang ringkas dan artikel pendukung yang menjawab pertanyaan calon pembeli. Dengan Aiticms-Lite, dua kebutuhan ini bisa dikelola dalam satu sistem yang sederhana.</p><ul><li>Mudah membuat halaman promosi produk</li><li>Bisa dipadukan dengan artikel edukatif</li><li>Konten lebih mudah diupdate sesuai kebutuhan pasar</li><li>Cocok untuk produk digital dan jasa online</li></ul><p>Jika Anda menjual template, layanan digital, atau software, Aiticms-Lite memberi struktur yang cukup fleksibel untuk memperkuat presentasi produk di website resmi.</p>', NULL, 'website bisnis,landing page,blog bisnis', '2026-03-10 09:11:00', '2026-03-10 09:11:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'alasan-memilih-aiticms-lite-untuk-website-produk-digital');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'aiticms-lite-mendukung-pengelolaan-artikel-yang-konsisten', 1, 'Aiticms-Lite Mendukung Pengelolaan Artikel yang Konsisten', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-12.svg', '<p>Konsistensi publikasi adalah tantangan besar dalam strategi konten. Aiticms-Lite membantu tim menjaga ritme produksi artikel karena alur input kontennya sederhana dan tidak membingungkan. Semakin mudah proses menulis dan menerbitkan konten, semakin besar peluang website tumbuh secara organik.</p><h2>Konsistensi lebih mudah dijaga</h2><p>Artikel yang dipublikasikan secara rutin akan membangun otoritas topik. Dengan dukungan slug, tag, dan struktur halaman baca yang rapi, Aiticms-Lite membantu tim menjalankan kalender editorial dengan lebih tertib.</p><ul><li>Memudahkan workflow artikel rutin</li><li>Membantu pengelompokan topik lewat tag</li><li>Cocok untuk strategi konten jangka panjang</li><li>Efisien untuk tim editorial kecil</li></ul><p>Aiticms-Lite bukan hanya mudah dipakai, tetapi juga mendukung disiplin publikasi yang dibutuhkan agar blog bisnis berkembang secara stabil.</p>', NULL, 'blog bisnis,manajemen konten,produktivitas tim', '2026-03-10 09:12:00', '2026-03-10 09:12:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'aiticms-lite-mendukung-pengelolaan-artikel-yang-konsisten');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'kelebihan-aiticms-lite-untuk-pengembangan-cepat', 2, 'Kelebihan Aiticms-Lite untuk Pengembangan Cepat', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-13.svg', '<p>Bisnis sering membutuhkan website yang bisa segera digunakan lalu dikembangkan bertahap. Aiticms-Lite mendukung pendekatan tersebut karena fondasinya sederhana, mudah dipasang, dan mudah diisi konten. Ini sangat membantu saat website perlu tayang cepat untuk kebutuhan promosi atau validasi pasar.</p><h2>Lebih cepat dari sisi implementasi</h2><p>CMS yang ringan mempercepat proses setup dan mengurangi waktu adaptasi tim. Setelah website aktif, pengembangan konten dan penyesuaian halaman dapat dilakukan secara bertahap tanpa membebani operasional.</p><ul><li>Implementasi awal lebih efisien</li><li>Konten inti dapat segera dipublikasikan</li><li>Cocok untuk pengembangan website bertahap</li><li>Menghemat waktu tim internal</li></ul><p>Aiticms-Lite relevan untuk startup, UMKM, agensi, maupun perusahaan yang membutuhkan CMS praktis agar website bisa bergerak cepat mengikuti target bisnis.</p>', NULL, 'cms ringan,website bisnis,company profile', '2026-03-10 09:13:00', '2026-03-10 09:13:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'kelebihan-aiticms-lite-untuk-pengembangan-cepat');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'aiticms-lite-untuk-website-perusahaan-yang-profesional', 3, 'Aiticms-Lite untuk Website Perusahaan yang Profesional', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-14.svg', '<p>Website perusahaan perlu terlihat profesional, informatif, dan mudah dinavigasi. Aiticms-Lite membantu mewujudkan itu dengan struktur yang sederhana tetapi cukup fleksibel untuk menampilkan profil, layanan, kontak, dan artikel pendukung. Hasilnya adalah website yang enak dibuka dan mudah dikelola.</p><h2>Profesional tanpa beban sistem berlebih</h2><p>Perusahaan tidak selalu membutuhkan platform besar untuk membangun citra digital. Yang dibutuhkan adalah CMS yang stabil, mudah dioperasikan, dan mendukung pembaruan konten secara rutin. Aiticms-Lite memberi nilai tersebut.</p><ul><li>Tepat untuk company profile modern</li><li>Memudahkan update informasi perusahaan</li><li>Mendukung artikel untuk memperkuat kredibilitas</li><li>Cocok untuk website resmi berbagai sektor bisnis</li></ul><p>Bagi perusahaan yang ingin website profesional dengan pengelolaan efisien, Aiticms-Lite adalah pilihan yang rasional dan mudah dikembangkan.</p>', NULL, 'company profile,website bisnis,custom tema', '2026-03-10 09:14:00', '2026-03-10 09:14:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'aiticms-lite-untuk-website-perusahaan-yang-profesional');

INSERT INTO `article` (`slug_article`, `user_id`, `title`, `title_en`, `category_id`, `subkat_id`, `images`, `content`, `content_en`, `tags`, `created_at`, `updated_at`, `publish`, `comment_active`, `counter`)
SELECT 'aiticms-lite-cms-seo-friendly-untuk-pertumbuhan-organik', 1, 'Aiticms-Lite, CMS SEO Friendly untuk Pertumbuhan Organik', NULL, 24, NULL, '/assets/img/artikel/seo-aiticms-lite-15.svg', '<p>Pertumbuhan organik membutuhkan website yang cepat, rapi, dan mudah diisi konten baru. Aiticms-Lite mendukung kebutuhan tersebut melalui struktur artikel yang jelas, manajemen tag yang sederhana, dan performa yang ringan. Kombinasi ini membuat CMS lebih siap dipakai untuk strategi SEO jangka panjang.</p><h2>Fondasi baik untuk SEO organik</h2><p>SEO bukan sekadar soal kata kunci, tetapi juga soal pengalaman pengguna, konsistensi konten, dan struktur website. Aiticms-Lite membantu bisnis membangun tiga area itu dengan pendekatan yang efisien dan tidak berlebihan.</p><ul><li>Ringan untuk mendukung performa halaman</li><li>Mudah digunakan untuk publikasi artikel SEO</li><li>Struktur konten membantu pengembangan topik</li><li>Cocok untuk website bisnis yang ingin tumbuh organik</li></ul><p>Jika target Anda adalah trafik organik yang lebih sehat dan website yang tetap mudah dikelola, Aiticms-Lite adalah fondasi CMS yang relevan untuk digunakan.</p>', NULL, 'seo cms,cms ringan,blog bisnis', '2026-03-10 09:15:00', '2026-03-10 09:15:00', 'P', 'Y', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM `article` WHERE `slug_article` = 'aiticms-lite-cms-seo-friendly-untuk-pertumbuhan-organik');
